import React from "react";
import Footer from "./Footer";
import Head from "next/head";
import Header from "./header";
import ListContact from "./common/ListContact";

type Props = {
  children: JSX.Element;
  title?: string;
};

const MainLayout = ({ children, title }: Props) => {
  return (
    <>
      <Head>
        <title>{title || "Mỹ thuật Đông Anh"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/png/logo.png" />
      </Head>
      <Header />
      {children}
      <ListContact />
      <Footer />
    </>
  );
};

export default MainLayout;
